# Generated by Django 3.2 on 2022-07-06 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sokoapp', '0003_alter_order_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cloth',
            name='photo',
            field=models.ImageField(upload_to='product/'),
        ),
        migrations.AlterField(
            model_name='order',
            name='item',
            field=models.ManyToManyField(to='sokoapp.OrderItem'),
        ),
    ]
