# Generated by Django 3.2 on 2022-07-06 11:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sokoapp', '0004_auto_20220706_1110'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cloth',
            new_name='Item',
        ),
        migrations.AlterField(
            model_name='order',
            name='item',
            field=models.ManyToManyField(to='sokoapp.OrderItem'),
        ),
    ]
