# Generated by Django 3.2 on 2022-07-06 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sokoapp', '0005_auto_20220706_1113'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='order',
            name='item',
            field=models.ManyToManyField(to='sokoapp.OrderItem'),
        ),
    ]
