# Generated by Django 3.2 on 2022-07-07 05:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sokoapp', '0009_auto_20220706_1526'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartproduct',
            old_name='subtotal',
            new_name='total_item',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='date',
        ),
        migrations.AddField(
            model_name='cart',
            name='ordered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cartproduct',
            name='price',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cartproduct',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
