# Generated by Django 3.2 on 2022-07-07 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sokoapp', '0010_auto_20220707_0522'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartproduct',
            name='total_item',
        ),
        migrations.AddField(
            model_name='cart',
            name='product',
            field=models.ManyToManyField(blank=True, to='sokoapp.Product'),
        ),
    ]
