# Generated by Django 3.2 on 2022-07-07 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sokoapp', '0011_auto_20220707_0543'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='product',
            new_name='products',
        ),
    ]
