# Generated by Django 3.2 on 2022-07-07 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sokoapp', '0017_auto_20220707_1102'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('name',)},
        ),
        migrations.AlterIndexTogether(
            name='product',
            index_together={('id', 'slug')},
        ),
    ]
