# Generated by Django 3.2 on 2022-07-07 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sokoapp', '0019_product_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='quantity',
        ),
    ]
