# Generated by Django 3.2 on 2022-07-09 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_auto_20220709_1125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_options',
            field=models.BooleanField(choices=[('Paypal', 'Paypal'), ('M-pesa', 'M-pesa'), ('stripe', 'stripe')], default=False),
        ),
    ]
