# Generated by Django 3.2 on 2022-07-09 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0007_order_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='Country',
        ),
        migrations.RemoveField(
            model_name='order',
            name='payment_options',
        ),
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
        migrations.RemoveField(
            model_name='order',
            name='zip',
        ),
    ]
